/*
Joseph A. Chandler
email: chandlerjoe64@gmail.com
*/

/*
EXTAN (tEXT_ANanlysis) is a program which iterates over a given 
body of text to derive repeated patters of words. Its purpose 
is to identify phrases or other repeating patterns to aid in the 
creation of password dictionaries.
*/

#include<stdio.h>
#include<stdlib.h>
#include "extan.h"


int main(int argc, char*argv[]) {
   	
	//initialize file pointers
	FILE *input_text;
	FILE *formatted_text;
	FILE *checked_list;
	FILE *found_list;

	//open files for execution and perform error checks
	input_text = fopen("Harry Potter and the Sorcerer's Stone.txt", "r");
	if(input_text == NULL) {
		printf("Failed to open input file...\nExiting...\n");
		exit(0);
	}

	formatted_text = fopen("tmp/formatted.txt", "w+");
	if(formatted_text == NULL) {
		printf("Failed to initialize output file...\nExiting...\n");
		exit(0);
	}

	found_list = fopen("tmp/found.txt", "w");
	if(found_list == NULL) {
		printf("Failed to initialize found file...\nExiting...\n");
	}

	//execute format_text to sanatize input text
    format_text(input_text, formatted_text);

    //determine word count of formatted.txt
	unsigned int count;
	FILE* wc = popen("wc -w < tmp/formatted.txt", "r");	//open stream to system for wc call
	fscanf(wc, "%d", &count);	//read command output from the stream and store it in count
	pclose(wc);	//close stream     

	//reopen formatted_text in r mode to avoid overwriting when rewinding in format_text
	formatted_text = fopen("tmp/formatted.txt", "r");
	if(formatted_text == NULL) {
		printf("Failed to initialize output file...\nExiting...\n");
		exit(0);
	}

	//initialize words and populate array
	char* words[count];
	populate_array(words, formatted_text);
	words[count] = NULL;	//null terminate the array


	//set length of strings (max number of words per string) to check
	int lengthToCheck = 4;

	//formula to determine number of strings generated by generate_check_strings
	// (count*(length-1))-((((length-2)*(length-1))/2)+(length-1))
	//determine length of check_strings
	unsigned int check_count = (count*(lengthToCheck-1))-((((lengthToCheck-2)*(lengthToCheck-1))/2)+(lengthToCheck-1));

	//initialze check_strings
	char** check_strings = malloc(sizeof(char*) * check_count);
	//check_strings[check_count] = NULL;

	//populate check_strings with generate_check_strings
	generate_check_strings(lengthToCheck, words, check_strings);

	//check for duplicate strings
	int threshold = 5;	//threshold for how many times a string must appear to be considered repeated
	check_for_duplicates(check_strings, check_count, threshold, found_list);

	//tidy up
	//close arrays
	free_array(words, count);

	free_array(check_strings, check_count);
	free(check_strings);

	//close file pointers
	fclose(input_text);
	fclose(formatted_text);
	
	//remove tmp files after execution
	//system("exec rm -r tmp/*");
}
